package main.Enums;

public enum RequestType {
    SIGNUP,
    LOGIN,
    CHECK_PERSON,
    GET_USERS,
    GIVE_ROLE,
    DELETE_USER,
    ADD_CAR,
    DELETE_CAR,
    GET_CARS,
    GET_TEST_DRIVES,
    GET_CAR_REQUESTS,
    SET_REQUEST_STATUS,
    SET_TEST_DRIVE_STATUS,
    REGISTRATE_REQUEST,
    SAVE_TEST_DRIVE,
    ADD_FAVORITE,
    GET_FAVORITES,
    DELETE_TEST_DRIVE,
    DELETE_FAVORITE
}
